<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:14:38.
 */
class uploadImageModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var uploadImageModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new uploadImageModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers uploadImageModel::upload
     * @todo   Implement testUpload().
     */
    public function testUpload() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers uploadImageModel::getUrl
     * @todo   Implement testGetUrl().
     */
    public function testGetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers uploadImageModel::load
     * @todo   Implement testLoad().
     */
    public function testLoad() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers uploadImageModel::apagar
     * @todo   Implement testApagar().
     */
    public function testApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers uploadImageModel::setCapa
     * @todo   Implement testSetCapa().
     */
    public function testSetCapa() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers uploadImageModel::getCapa
     * @todo   Implement testGetCapa().
     */
    public function testGetCapa() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers uploadImageModel::getImagesPath
     * @todo   Implement testGetImagesPath().
     */
    public function testGetImagesPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers uploadImageModel::getExtension
     * @todo   Implement testGetExtension().
     */
    public function testGetExtension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers uploadImageModel::getImgFromDatabase
     * @todo   Implement testGetImgFromDatabase().
     */
    public function testGetImgFromDatabase() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers uploadImageModel::draw
     * @todo   Implement testDraw().
     */
    public function testDraw() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
