<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:14:37.
 */
class UploaderImagesHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UploaderImagesHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UploaderImagesHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers UploaderImagesHelper::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UploaderImagesHelper::Upload
     * @todo   Implement testUpload().
     */
    public function testUpload() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UploaderImagesHelper::getUploadedImages
     * @todo   Implement testGetUploadedImages().
     */
    public function testGetUploadedImages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UploaderImagesHelper::getNames
     * @todo   Implement testGetNames().
     */
    public function testGetNames() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UploaderImagesHelper::getPaths
     * @todo   Implement testGetPaths().
     */
    public function testGetPaths() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UploaderImagesHelper::getExtension
     * @todo   Implement testGetExtension().
     */
    public function testGetExtension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UploaderImagesHelper::drop
     * @todo   Implement testDrop().
     */
    public function testDrop() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
