<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:12:02.
 */
class phpthumb_icoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var phpthumb_ico
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new phpthumb_ico;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers phpthumb_ico::GD2ICOstring
     * @todo   Implement testGD2ICOstring().
     */
    public function testGD2ICOstring() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
