<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:12:03.
 */
class phpthumb_bmpTest extends PHPUnit_Framework_TestCase {

    /**
     * @var phpthumb_bmp
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new phpthumb_bmp;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers phpthumb_bmp::phpthumb_bmp2gd
     * @todo   Implement testPhpthumb_bmp2gd().
     */
    public function testPhpthumb_bmp2gd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::phpthumb_bmpfile2gd
     * @todo   Implement testPhpthumb_bmpfile2gd().
     */
    public function testPhpthumb_bmpfile2gd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::GD2BMPstring
     * @todo   Implement testGD2BMPstring().
     */
    public function testGD2BMPstring() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::getid3_bmp
     * @todo   Implement testGetid3_bmp().
     */
    public function testGetid3_bmp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::IntColor2RGB
     * @todo   Implement testIntColor2RGB().
     */
    public function testIntColor2RGB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::PlotPixelsGD
     * @todo   Implement testPlotPixelsGD().
     */
    public function testPlotPixelsGD() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::PlotBMP
     * @todo   Implement testPlotBMP().
     */
    public function testPlotBMP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::BMPcompressionWindowsLookup
     * @todo   Implement testBMPcompressionWindowsLookup().
     */
    public function testBMPcompressionWindowsLookup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::BMPcompressionOS2Lookup
     * @todo   Implement testBMPcompressionOS2Lookup().
     */
    public function testBMPcompressionOS2Lookup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::trunc
     * @todo   Implement testTrunc().
     */
    public function testTrunc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::LittleEndian2Int
     * @todo   Implement testLittleEndian2Int().
     */
    public function testLittleEndian2Int() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::BigEndian2Int
     * @todo   Implement testBigEndian2Int().
     */
    public function testBigEndian2Int() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::BigEndian2Bin
     * @todo   Implement testBigEndian2Bin().
     */
    public function testBigEndian2Bin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::FixedPoint2_30
     * @todo   Implement testFixedPoint2_30().
     */
    public function testFixedPoint2_30() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::Bin2Dec
     * @todo   Implement testBin2Dec().
     */
    public function testBin2Dec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_bmp::CastAsInt
     * @todo   Implement testCastAsInt().
     */
    public function testCastAsInt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
