<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:12:01.
 */
class phpthumb_functionsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var phpthumb_functions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new phpthumb_functions;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers phpthumb_functions::user_function_exists
     * @todo   Implement testUser_function_exists().
     */
    public function testUser_function_exists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::builtin_function_exists
     * @todo   Implement testBuiltin_function_exists().
     */
    public function testBuiltin_function_exists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::version_compare_replacement_sub
     * @todo   Implement testVersion_compare_replacement_sub().
     */
    public function testVersion_compare_replacement_sub() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::version_compare_replacement
     * @todo   Implement testVersion_compare_replacement().
     */
    public function testVersion_compare_replacement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::phpinfo_array
     * @todo   Implement testPhpinfo_array().
     */
    public function testPhpinfo_array() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::exif_info
     * @todo   Implement testExif_info().
     */
    public function testExif_info() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::ImageTypeToMIMEtype
     * @todo   Implement testImageTypeToMIMEtype().
     */
    public function testImageTypeToMIMEtype() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::TranslateWHbyAngle
     * @todo   Implement testTranslateWHbyAngle().
     */
    public function testTranslateWHbyAngle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::HexCharDisplay
     * @todo   Implement testHexCharDisplay().
     */
    public function testHexCharDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::IsHexColor
     * @todo   Implement testIsHexColor().
     */
    public function testIsHexColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::ImageColorAllocateAlphaSafe
     * @todo   Implement testImageColorAllocateAlphaSafe().
     */
    public function testImageColorAllocateAlphaSafe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::ImageHexColorAllocate
     * @todo   Implement testImageHexColorAllocate().
     */
    public function testImageHexColorAllocate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::HexColorXOR
     * @todo   Implement testHexColorXOR().
     */
    public function testHexColorXOR() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::GetPixelColor
     * @todo   Implement testGetPixelColor().
     */
    public function testGetPixelColor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::PixelColorDifferencePercent
     * @todo   Implement testPixelColorDifferencePercent().
     */
    public function testPixelColorDifferencePercent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::GrayscaleValue
     * @todo   Implement testGrayscaleValue().
     */
    public function testGrayscaleValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::GrayscalePixel
     * @todo   Implement testGrayscalePixel().
     */
    public function testGrayscalePixel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::GrayscalePixelRGB
     * @todo   Implement testGrayscalePixelRGB().
     */
    public function testGrayscalePixelRGB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::ScaleToFitInBox
     * @todo   Implement testScaleToFitInBox().
     */
    public function testScaleToFitInBox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::ImageCopyResampleBicubic
     * @todo   Implement testImageCopyResampleBicubic().
     */
    public function testImageCopyResampleBicubic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::ImageCreateFunction
     * @todo   Implement testImageCreateFunction().
     */
    public function testImageCreateFunction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::ImageCopyRespectAlpha
     * @todo   Implement testImageCopyRespectAlpha().
     */
    public function testImageCopyRespectAlpha() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::ProportionalResize
     * @todo   Implement testProportionalResize().
     */
    public function testProportionalResize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::FunctionIsDisabled
     * @todo   Implement testFunctionIsDisabled().
     */
    public function testFunctionIsDisabled() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::SafeExec
     * @todo   Implement testSafeExec().
     */
    public function testSafeExec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::ApacheLookupURIarray
     * @todo   Implement testApacheLookupURIarray().
     */
    public function testApacheLookupURIarray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::gd_is_bundled
     * @todo   Implement testGd_is_bundled().
     */
    public function testGd_is_bundled() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::gd_version
     * @todo   Implement testGd_version().
     */
    public function testGd_version() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::filesize_remote
     * @todo   Implement testFilesize_remote().
     */
    public function testFilesize_remote() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::filedate_remote
     * @todo   Implement testFiledate_remote().
     */
    public function testFiledate_remote() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::md5_file_safe
     * @todo   Implement testMd5_file_safe().
     */
    public function testMd5_file_safe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::nonempty_min
     * @todo   Implement testNonempty_min().
     */
    public function testNonempty_min() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::LittleEndian2String
     * @todo   Implement testLittleEndian2String().
     */
    public function testLittleEndian2String() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::OneOfThese
     * @todo   Implement testOneOfThese().
     */
    public function testOneOfThese() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::CaseInsensitiveInArray
     * @todo   Implement testCaseInsensitiveInArray().
     */
    public function testCaseInsensitiveInArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::URLreadFsock
     * @todo   Implement testURLreadFsock().
     */
    public function testURLreadFsock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::CleanUpURLencoding
     * @todo   Implement testCleanUpURLencoding().
     */
    public function testCleanUpURLencoding() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::ParseURLbetter
     * @todo   Implement testParseURLbetter().
     */
    public function testParseURLbetter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::SafeURLread
     * @todo   Implement testSafeURLread().
     */
    public function testSafeURLread() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::EnsureDirectoryExists
     * @todo   Implement testEnsureDirectoryExists().
     */
    public function testEnsureDirectoryExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::GetAllFilesInSubfolders
     * @todo   Implement testGetAllFilesInSubfolders().
     */
    public function testGetAllFilesInSubfolders() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_functions::SanitizeFilename
     * @todo   Implement testSanitizeFilename().
     */
    public function testSanitizeFilename() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
