<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:12:03.
 */
class phpUnsharpMaskTest extends PHPUnit_Framework_TestCase {

    /**
     * @var phpUnsharpMask
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new phpUnsharpMask;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers phpUnsharpMask::applyUnsharpMask
     * @todo   Implement testApplyUnsharpMask().
     */
    public function testApplyUnsharpMask() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
