<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:12:04.
 */
class phpthumb_filtersTest extends PHPUnit_Framework_TestCase {

    /**
     * @var phpthumb_filters
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new phpthumb_filters;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers phpthumb_filters::ApplyMask
     * @todo   Implement testApplyMask().
     */
    public function testApplyMask() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Bevel
     * @todo   Implement testBevel().
     */
    public function testBevel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Blur
     * @todo   Implement testBlur().
     */
    public function testBlur() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::BlurGaussian
     * @todo   Implement testBlurGaussian().
     */
    public function testBlurGaussian() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::BlurSelective
     * @todo   Implement testBlurSelective().
     */
    public function testBlurSelective() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Brightness
     * @todo   Implement testBrightness().
     */
    public function testBrightness() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Contrast
     * @todo   Implement testContrast().
     */
    public function testContrast() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Colorize
     * @todo   Implement testColorize().
     */
    public function testColorize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Crop
     * @todo   Implement testCrop().
     */
    public function testCrop() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Desaturate
     * @todo   Implement testDesaturate().
     */
    public function testDesaturate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::DropShadow
     * @todo   Implement testDropShadow().
     */
    public function testDropShadow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::EdgeDetect
     * @todo   Implement testEdgeDetect().
     */
    public function testEdgeDetect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Elipse
     * @todo   Implement testElipse().
     */
    public function testElipse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Emboss
     * @todo   Implement testEmboss().
     */
    public function testEmboss() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Flip
     * @todo   Implement testFlip().
     */
    public function testFlip() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Frame
     * @todo   Implement testFrame().
     */
    public function testFrame() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Gamma
     * @todo   Implement testGamma().
     */
    public function testGamma() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Grayscale
     * @todo   Implement testGrayscale().
     */
    public function testGrayscale() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::HistogramAnalysis
     * @todo   Implement testHistogramAnalysis().
     */
    public function testHistogramAnalysis() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::HistogramStretch
     * @todo   Implement testHistogramStretch().
     */
    public function testHistogramStretch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::HistogramOverlay
     * @todo   Implement testHistogramOverlay().
     */
    public function testHistogramOverlay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::ImageBorder
     * @todo   Implement testImageBorder().
     */
    public function testImageBorder() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::ImprovedImageRotate
     * @todo   Implement testImprovedImageRotate().
     */
    public function testImprovedImageRotate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::MeanRemoval
     * @todo   Implement testMeanRemoval().
     */
    public function testMeanRemoval() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Negative
     * @todo   Implement testNegative().
     */
    public function testNegative() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::RoundedImageCorners
     * @todo   Implement testRoundedImageCorners().
     */
    public function testRoundedImageCorners() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Saturation
     * @todo   Implement testSaturation().
     */
    public function testSaturation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Sepia
     * @todo   Implement testSepia().
     */
    public function testSepia() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Smooth
     * @todo   Implement testSmooth().
     */
    public function testSmooth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::SourceTransparentColorMask
     * @todo   Implement testSourceTransparentColorMask().
     */
    public function testSourceTransparentColorMask() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::Threshold
     * @todo   Implement testThreshold().
     */
    public function testThreshold() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::ImageTrueColorToPalette2
     * @todo   Implement testImageTrueColorToPalette2().
     */
    public function testImageTrueColorToPalette2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::ReduceColorDepth
     * @todo   Implement testReduceColorDepth().
     */
    public function testReduceColorDepth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::WhiteBalance
     * @todo   Implement testWhiteBalance().
     */
    public function testWhiteBalance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::WatermarkText
     * @todo   Implement testWatermarkText().
     */
    public function testWatermarkText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::WatermarkOverlay
     * @todo   Implement testWatermarkOverlay().
     */
    public function testWatermarkOverlay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb_filters::DebugMessage
     * @todo   Implement testDebugMessage().
     */
    public function testDebugMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
