<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:12:01.
 */
class phpthumbTest extends PHPUnit_Framework_TestCase {

    /**
     * @var phpthumb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new phpthumb;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers phpthumb::setSourceFilename
     * @todo   Implement testSetSourceFilename().
     */
    public function testSetSourceFilename() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::setSourceData
     * @todo   Implement testSetSourceData().
     */
    public function testSetSourceData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::setSourceImageResource
     * @todo   Implement testSetSourceImageResource().
     */
    public function testSetSourceImageResource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::setParameter
     * @todo   Implement testSetParameter().
     */
    public function testSetParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::getParameter
     * @todo   Implement testGetParameter().
     */
    public function testGetParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::GenerateThumbnail
     * @todo   Implement testGenerateThumbnail().
     */
    public function testGenerateThumbnail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::RenderOutput
     * @todo   Implement testRenderOutput().
     */
    public function testRenderOutput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::RenderToFile
     * @todo   Implement testRenderToFile().
     */
    public function testRenderToFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::OutputThumbnail
     * @todo   Implement testOutputThumbnail().
     */
    public function testOutputThumbnail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::CleanUpCacheDirectory
     * @todo   Implement testCleanUpCacheDirectory().
     */
    public function testCleanUpCacheDirectory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::resetObject
     * @todo   Implement testResetObject().
     */
    public function testResetObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ResolveSource
     * @todo   Implement testResolveSource().
     */
    public function testResolveSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::setOutputFormat
     * @todo   Implement testSetOutputFormat().
     */
    public function testSetOutputFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::setCacheDirectory
     * @todo   Implement testSetCacheDirectory().
     */
    public function testSetCacheDirectory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ResolveFilenameToAbsolute
     * @todo   Implement testResolveFilenameToAbsolute().
     */
    public function testResolveFilenameToAbsolute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ImageMagickWhichConvert
     * @todo   Implement testImageMagickWhichConvert().
     */
    public function testImageMagickWhichConvert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ImageMagickCommandlineBase
     * @todo   Implement testImageMagickCommandlineBase().
     */
    public function testImageMagickCommandlineBase() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ImageMagickVersion
     * @todo   Implement testImageMagickVersion().
     */
    public function testImageMagickVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ImageMagickSwitchAvailable
     * @todo   Implement testImageMagickSwitchAvailable().
     */
    public function testImageMagickSwitchAvailable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ImageMagickFormatsList
     * @todo   Implement testImageMagickFormatsList().
     */
    public function testImageMagickFormatsList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::SourceDataToTempFile
     * @todo   Implement testSourceDataToTempFile().
     */
    public function testSourceDataToTempFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ImageMagickThumbnailToGD
     * @todo   Implement testImageMagickThumbnailToGD().
     */
    public function testImageMagickThumbnailToGD() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::Rotate
     * @todo   Implement testRotate().
     */
    public function testRotate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::FixedAspectRatio
     * @todo   Implement testFixedAspectRatio().
     */
    public function testFixedAspectRatio() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::OffsiteDomainIsAllowed
     * @todo   Implement testOffsiteDomainIsAllowed().
     */
    public function testOffsiteDomainIsAllowed() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::AntiOffsiteLinking
     * @todo   Implement testAntiOffsiteLinking().
     */
    public function testAntiOffsiteLinking() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::AlphaChannelFlatten
     * @todo   Implement testAlphaChannelFlatten().
     */
    public function testAlphaChannelFlatten() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ApplyFilters
     * @todo   Implement testApplyFilters().
     */
    public function testApplyFilters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::MaxFileSize
     * @todo   Implement testMaxFileSize().
     */
    public function testMaxFileSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::CalculateThumbnailDimensions
     * @todo   Implement testCalculateThumbnailDimensions().
     */
    public function testCalculateThumbnailDimensions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::CreateGDoutput
     * @todo   Implement testCreateGDoutput().
     */
    public function testCreateGDoutput() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::SetOrientationDependantWidthHeight
     * @todo   Implement testSetOrientationDependantWidthHeight().
     */
    public function testSetOrientationDependantWidthHeight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ExtractEXIFgetImageSize
     * @todo   Implement testExtractEXIFgetImageSize().
     */
    public function testExtractEXIFgetImageSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::SetCacheFilename
     * @todo   Implement testSetCacheFilename().
     */
    public function testSetCacheFilename() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::SourceImageIsTooLarge
     * @todo   Implement testSourceImageIsTooLarge().
     */
    public function testSourceImageIsTooLarge() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ImageCreateFromFilename
     * @todo   Implement testImageCreateFromFilename().
     */
    public function testImageCreateFromFilename() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::SourceImageToGD
     * @todo   Implement testSourceImageToGD().
     */
    public function testSourceImageToGD() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::phpThumbDebugVarDump
     * @todo   Implement testPhpThumbDebugVarDump().
     */
    public function testPhpThumbDebugVarDump() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::phpThumbDebug
     * @todo   Implement testPhpThumbDebug().
     */
    public function testPhpThumbDebug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::FatalError
     * @todo   Implement testFatalError().
     */
    public function testFatalError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ErrorImage
     * @todo   Implement testErrorImage().
     */
    public function testErrorImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ImageCreateFromStringReplacement
     * @todo   Implement testImageCreateFromStringReplacement().
     */
    public function testImageCreateFromStringReplacement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::ImageResizeFunction
     * @todo   Implement testImageResizeFunction().
     */
    public function testImageResizeFunction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::InitializeTempDirSetting
     * @todo   Implement testInitializeTempDirSetting().
     */
    public function testInitializeTempDirSetting() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::phpThumb_tempnam
     * @todo   Implement testPhpThumb_tempnam().
     */
    public function testPhpThumb_tempnam() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::DebugMessage
     * @todo   Implement testDebugMessage().
     */
    public function testDebugMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers phpthumb::DebugTimingMessage
     * @todo   Implement testDebugTimingMessage().
     */
    public function testDebugTimingMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
